# Generated by Django 4.0.4 on 2022-05-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmatcher', '0002_remove_candidate_skills_candidate_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(to='jobmatcher.skill'),
        ),
    ]
